model:
    name: 'MLPRULPredictor'
    in_channels: 1
    channels: 32
    input_height: 1
    input_width: 1000
    epochs: 5000
    batch_size: 128
    evaluate_freq: 100
train_test_split:
    name: 'SNLTrainTestSplitter'
    cell_data_path: 'data/processed/SNL'
feature:
    name: 'VoltageCapacityMatrixFeatureExtractor'
    diff_base: 2
    cycles_to_keep: 19
    max_cycle_index: 19
label:
    name: 'RULLabelAnnotator'
    eol_soh: 0.9
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
