model:
    name: 'LinearRegressionRULPredictor'
train_test_split:
    name: 'SNLTrainTestSplitter'
    cell_data_path: 'data/processed/SNL'
feature:
    name: 'VarianceModelFeatureExtractor'
    interp_dims: 1000
    critical_cycles:
        - 2
        - 9
        - 19
label:
    name: 'RULLabelAnnotator'
    eol_soh: 0.9
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
